import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import FreshnessBanner from "@/components/FreshnessBanner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <FreshnessBanner />
        {children}
        <Footer />
      </body>
    </html>
  );
}
